version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: database_container
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: ./ProdutoCategoria
      dockerfile: Dockerfile
    container_name: backend_container
    ports:
      - "8080:8080"
      - "8585:8585" #DEBUG
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/database
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

  angular-app:
    build:
      context: ./ProdutoCategoriaFront
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
      - postgres

volumes:
  postgres_data:
